app.config(function($stateProvider,$urlRouterProvider){
	$stateProvider
	.state("person",{
		url:"/person",
		templateUrl:"view/person/person.html",
		controller:"personCtrl"
	})
	.state("song",{
		url:"/song",
		templateUrl:"view/song/song.html",
		controller:"songCtrl"
	})
	.state("radio",{
		url:"/radio",
		templateUrl:"view/radio/radio.html",
		controller:"radioCtrl"
	})
	.state("list",{
		url:"/list",
		templateUrl:"view/list/list.html",
		controller:"listCtrl"
	})
	.state("friend",{
		url:"/friend",
		templateUrl:"view/friend/friend.html",
		controller:"friendCtrl"
	})
	.state("music",{
		url:"/music",
		templateUrl:"view/music/music.html",
		controller:"musicCtrl"
	})
	.state("my",{
		url:"/my",
		templateUrl:"view/my/my.html",
		controller:"myCtrl"
	})
	$urlRouterProvider.otherwise("person")
})
